
spring:
  application:
    name: wlog-web
  profiles:
    active: dev
#    active: prod

#  返回参数如果为null就不返回
#  jackson:
#    # 设置后台返参，若字段值为 null, 则不返回
#    default-property-inclusion: non_null
#    # 设置日期字段格式
#    date-format: yyyy-MM-dd HH:mm:ss
liteflow:
  #规则文件路径
  rule-source: config/flow.xml
  #liteflow是否开启，默认为true
  enable: true

wlog:
  info:
    development: ${spring.profiles.active}
    serviceName: ${spring.application.name}
    swagger: http://127.0.0.1:11002/doc.html